alias c="clear"
alias pn="pnpm"
alias gaa="git add -A"
alias gac="git add -A && git commit -m"

alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dcp="docker compose pull"
alias dcr="docker compose restart"
alias dclog="docker compose logs -f"
alias dctail="docker compose logs --tail 100"
