alias c="clear"
alias pn="pnpm"
alias gaa="git add -A"
alias gac="git add -A && git commit -m"

alias dc="docker compose"
alias dcup="docker compose up -d"
alias dcdown="docker compose down"
alias dcexec="docker compose exec"
alias dcr="docker compose restart"
alias dcl="docker compose logs -f"
alias dcltail="docker compose logs --tail 200"
